### ISSUE TITLE
validation oddity

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#130] opened 2019-03-11 23:52 UTC
In some of the Apa Johannes documents, the metadata validates in spreadsheet mode, but in the list of docs, the little tag icon for metadata is red. Hovering over the tag reveals a message that "Metadata for license does not match pattern." I can't figure out why this message doesn't appear in the spreadsheet editor window when you validate, nor can I figure out how to fix the validation error. Thanks so much!

**Comment by amir-zeldes** [comment] 2019-03-13 21:39
Hm.. This seems to be a bug with validation caching. I'm not sure what's causing it since I'm not 100% up to date with the validator code. @lgessler could you have a look? I can confirm that:

johannes.canons.FA205-252

Has different validation warnings on the dashboard and if you hit validate inside the document. Editing something does not reset the dashboard validation, even though hypothetically it should get the time stamp, notice that it's new and rerun validation on dashboard.

**Comment by amir-zeldes** [comment] 2019-03-13 22:15
I just diffed validate.py and found this uncommitted change which I committed for completeness:

de920de6670448b06734d0a317ee2f482b8fd701

It looks sensible so I don't think we should revert it, but it doesn't seem to fix the problem either...

**Closed** 2019-07-27 15:04 UTC
